# Day 0: Linear Algebra

In [1]:
import numpy as np

Vector Operations

In [2]:
a = np.array([1, 2, 3]) # 3-vector
b = np.array([2, 3, 4]) # 3-vector
print('Vector a: ', a)
print('Vector b: ', b)
print('a+b=', a+b) # addition
print('a-b=', a-b) # subtraction
print('2*a=', 2*a) # scaling
print('Norm of a=', np.linalg.norm(a)) # norm (length)
print('a*b=', a*b) # multiple
print('Dot product of (a,b)=', np.dot(a,b)) # dot product
print('Cross product of (a,b)=', np.cross(a,b)) # cross product

Vector a:  [1 2 3]
Vector b:  [2 3 4]
a+b= [3 5 7]
a-b= [-1 -1 -1]
2*a= [2 4 6]
Norm of a= 3.74165738677
a*b= [ 2  6 12]
Dot product of (a,b)= 20
Cross product of (a,b)= [-1  2 -1]


Matrix Operations

In [3]:
A = np.array([[1, 2 ,3], 
              [1, 1 ,1]]) # 2x3 matrix
B = np.array([[2, 3, 4],
              [2, 2, 2]]) # 2x3 matrix
C = np.array([[3, 4, 5],
              [4, 5, 6],
              [5, 6, 7]]) # 3x4 matrix
print('Matrix A: \n', A)
print('Matrix B: \n', B)
print('A+B= \n', A+B) # addition
print('A-B= \n', A-B) # subtraction
print('2*A= \n', 2*A) # scaling
print('Determinant of C:', np.linalg.det(C)) # determinant
print('A*B= \n', A*B) # multiple
print('Matrix product of (A,C)= \n', np.dot(A,C)) # dot product

Matrix A: 
 [[1 2 3]
 [1 1 1]]
Matrix B: 
 [[2 3 4]
 [2 2 2]]
A+B= 
 [[3 5 7]
 [3 3 3]]
A-B= 
 [[-1 -1 -1]
 [-1 -1 -1]]
2*A= 
 [[2 4 6]
 [2 2 2]]
Determinant of C: 1.7763568394e-15
A*B= 
 [[ 2  6 12]
 [ 2  2  2]]
Matrix product of (A,C)= 
 [[26 32 38]
 [12 15 18]]


**Note**:
+ *AB$\neq$BA*
+ *A(BC)=(AB)C*

Matrix-Vector product

In [4]:
a = np.array([[5, 1 ,3], 
              [1, 1 ,1], 
              [1, 2 ,1]]) # 3x3 matrix
b = np.array([1, 2, 3]) # 3-vector
print(a.dot(b))
print(np.dot(a,b))
print(np.matmul(a,b))
print(a @ b)

[16  6  8]
[16  6  8]
[16  6  8]
[16  6  8]


Identity Matrix, One matrix, Zero matrix

In [5]:
A = np.eye(2)   # indentity matrix
B = np.ones(2)  # One matrix
C = np.zeros(2) # Zero matrix
print('Identity matrix A:\n', A)
print('One matrix B:\n',B)
print('Zero matrix C:\n',C)
D = np.ones((4,2))
print('One 4x2 matrix D:\n', D)

Identity matrix A:
 [[ 1.  0.]
 [ 0.  1.]]
One matrix B:
 [ 1.  1.]
Zero matrix C:
 [ 0.  0.]
One 4x2 matrix D:
 [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


Inverse and transpose of matrix A

In [6]:
A = np.array([[1,2,0],
              [0,5,6],
              [7,0,9]]) 
A_inv = np.linalg.inv(A) # inverse of matrix A (if matrix is singular)
I = np.dot(A_inv, A)
A_t = np.transpose(A) # transpose of matrix A
print('Matrix A:\n', A)
print('Inverse of A:\n', A_inv)
print('A * inv(A)=\n',I)
print('Transpose of A:', A_t)

Matrix A:
 [[1 2 0]
 [0 5 6]
 [7 0 9]]
Inverse of A:
 [[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]
A * inv(A)=
 [[  1.00000000e+00   0.00000000e+00   2.22044605e-16]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [ -5.55111512e-17   0.00000000e+00   1.00000000e+00]]
Transpose of A: [[1 0 7]
 [2 5 0]
 [0 6 9]]


Row space, column space, and rank of a matrix

In [7]:
A = np.array([[1,2,0],
              [0,5,6],
              [7,0,9]]) # 3x3 matrix
print('Row space of A:\n', A[0,:], A[1,:], A[2,:])
print('Column space of A:\n', A[:,0], A[:,1], A[:,2])
print('Rank of A:\n', np.linalg.matrix_rank(A))

Row space of A:
 [1 2 0] [0 5 6] [7 0 9]
Column space of A:
 [1 0 7] [2 5 0] [0 6 9]
Rank of A:
 3


Eigenvalues and eigenvectors

In [8]:
A = np.diag((1, 2, 3)) # 3x3 matrix
print('Matrix A:\n', A)
w, v = np.linalg.eig(A)
print('Eigenvalues and eigenvectors of A:\n', w, ',', v)

Matrix A:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Eigenvalues and eigenvectors of A:
 [ 1.  2.  3.] , [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
